import { Bath, BedDouble, Filter, Map, MapPin, ShieldCheck, SlidersHorizontal, Sparkles, Star, Wifi } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { PropertyCard } from '@/components/public/property-card'
import { createClient } from '@/lib/supabase/server'
import { createSupabasePropertyService } from '@/features/properties/property.service'

const destinations = ['Aizawl', 'Champhai', 'Lunglei', 'Serchhip']

export default async function StaysPage() {
  const db = await createClient()
  const service = createSupabasePropertyService(db)
  const properties = await service.listPublished()
  return <main className="bg-[#faf7f0]">
    <section className="border-b border-black/5 bg-[#173e33] text-white"><div className="mx-auto max-w-7xl px-4 py-9 md:px-6 lg:py-11"><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><div className="flex items-center gap-2 text-[#dbe8df]"><Sparkles className="size-4 text-[#dfac50]" /><span className="text-[10px] font-bold uppercase tracking-[.22em]">Stay local · Travel deeper</span></div><h1 className="mt-3 font-display text-4xl text-white md:text-5xl">Find your stay in Mizoram.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-white/65">Verified homes, thoughtful hosts and places worth slowing down for.</p></div><div className="flex flex-wrap items-center gap-2 text-xs text-white/65"><span className="rounded-full bg-white/10 px-3 py-1.5">{properties.length} stays</span><span className="rounded-full bg-white/10 px-3 py-1.5">Verified listings</span></div></div></div></section>

    <section className="sticky top-[72px] z-20 border-b border-black/5 bg-[#faf7f0]/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center gap-2 overflow-x-auto px-4 py-3 md:px-6"><Button variant="outline" size="sm" className="shrink-0 bg-white"><MapPin className="size-4" /> Anywhere in Mizoram</Button><Button variant="outline" size="sm" className="shrink-0 bg-white">12 Oct <span className="text-muted-foreground">→</span> 16 Oct</Button><Button variant="outline" size="sm" className="shrink-0 bg-white">2 adults</Button><Button size="sm" className="shrink-0 bg-[#154637] hover:bg-[#154637]/90">Search stays</Button></div></section>

    <div className="mx-auto max-w-7xl px-4 py-7 md:px-6"><div className="mb-6 flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#70827a]">Curated collection</p><h2 className="mt-1 text-2xl font-black tracking-tight">Stays guests can book with confidence</h2></div><div className="flex gap-2"><Button variant="outline" size="sm" className="bg-white"><SlidersHorizontal className="size-4" /> Sort by</Button><Button variant="outline" size="sm" className="bg-white"><Filter className="size-4" /> Filters</Button></div></div>

      <div className="grid gap-6 lg:grid-cols-[250px_1fr_340px]">
        <aside className="hidden lg:block"><div className="sticky top-36 space-y-4"><div className="rounded-3xl border border-black/5 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-bold">Filter stays</h2><span className="text-[10px] font-bold uppercase tracking-wide text-[#84938c]">{properties.length} results</span></div><div className="mt-5 space-y-5 text-sm"><div><p className="font-bold">Destination</p><div className="mt-3 grid grid-cols-2 gap-2">{destinations.map((destination) => <button key={destination} className="rounded-xl border border-[#e0e5e1] px-3 py-2 text-left text-xs font-semibold text-[#556860] transition hover:border-[#aac2b4] hover:bg-[#f5f9f5]">{destination}</button>)}</div></div><div><p className="font-bold">Property type</p><div className="mt-3 space-y-2 text-xs"><label className="flex items-center gap-2"><input type="checkbox" /> Homestay</label><label className="flex items-center gap-2"><input type="checkbox" /> Guesthouse</label><label className="flex items-center gap-2"><input type="checkbox" /> Lodge</label></div></div><div><p className="font-bold">Amenities</p><div className="mt-3 space-y-2 text-xs"><label className="flex items-center gap-2"><input type="checkbox" /> Wi-Fi</label><label className="flex items-center gap-2"><input type="checkbox" /> Breakfast</label><label className="flex items-center gap-2"><input type="checkbox" /> Parking</label><label className="flex items-center gap-2"><input type="checkbox" /> Attached bathroom</label></div></div></div></div><div className="rounded-3xl bg-[#eef3ee] p-5"><div className="flex items-center gap-2 text-[#1e6049]"><ShieldCheck className="size-4" /><span className="text-xs font-bold uppercase tracking-[.14em]">Why verified?</span></div><p className="mt-3 text-sm font-semibold leading-6 text-[#36564a]">We clearly distinguish platform verification from tourism registration.</p></div></div></aside>

        <div className="space-y-5">{properties.length ? properties.map((property) => <PropertyCard key={property.id} property={property} />) : <div className="rounded-3xl border-2 border-dashed border-[#d7dfd9] bg-white p-12 text-center"><MapPin className="mx-auto size-10 text-[#6d8278]" /><p className="mt-4 text-lg font-black">No stays are published yet</p><p className="mt-2 text-sm text-muted-foreground">The marketplace is ready for its first verified properties.</p></div>}
        </div>

        <aside className="hidden xl:block"><div className="sticky top-36 overflow-hidden rounded-3xl border border-black/5 bg-white shadow-sm"><div className="h-[430px] bg-[radial-gradient(circle_at_28%_28%,rgba(55,113,88,.18),transparent_28%),radial-gradient(circle_at_72%_64%,rgba(221,171,73,.15),transparent_30%),linear-gradient(145deg,#edf2eb,#f5f1e8)]"><div className="flex h-full flex-col items-center justify-center p-8 text-center"><div className="grid size-14 place-items-center rounded-2xl bg-white/75 text-[#1d5b47] shadow-sm"><Map className="size-6" /></div><p className="mt-5 text-xs font-bold uppercase tracking-[.18em] text-[#789087]">Explore by place</p><h3 className="mt-2 text-xl font-black">Stay close to what matters.</h3><p className="mt-2 max-w-[230px] text-sm leading-6 text-muted-foreground">Use the map to compare neighbourhoods, viewpoints and access before choosing a room.</p><Badge className="mt-5 bg-[#154637] text-white">Map ready</Badge></div></div><div className="grid grid-cols-2 border-t border-black/5 text-xs"><div className="flex items-center gap-2 border-r p-4 font-semibold"><BedDouble className="size-4 text-[#55746a]" /> Room type</div><div className="flex items-center gap-2 p-4 font-semibold"><Star className="size-4 fill-[#d4942f] text-[#d4942f]" /> Guest rating</div><div className="flex items-center gap-2 border-r border-t p-4 font-semibold"><Wifi className="size-4 text-[#55746a]" /> Amenities</div><div className="flex items-center gap-2 border-t p-4 font-semibold"><Bath className="size-4 text-[#55746a]" /> Bathrooms</div></div></div></aside>
      </div>
    </div>
    <div className="fixed inset-x-4 bottom-4 z-30 flex gap-2 xl:hidden"><Button className="flex-1 bg-[#154637] hover:bg-[#154637]/90"><Filter className="size-4" /> Filters</Button><Button variant="outline" className="flex-1 bg-white"><Map className="size-4" /> Map</Button></div>
  </main>
}
