import Link from 'next/link'
import { ArrowRight, Building2, CheckCircle2, MoreHorizontal, Search, ShieldAlert } from 'lucide-react'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'

const rows = [
  ['Mizoram Hills Homestay', 'Aizawl', 'Level 4', 'Published'],
  ['Green Valley Stay', 'Reiek', 'Level 5', 'Published'],
  ['Champhai Wine Country Stay', 'Champhai', 'Level 3', 'Pending review'],
  ['Thenzawl Forest Retreat', 'Thenzawl', 'Level 4', 'Published'],
]

export default function AdminPropertiesPage() {
  return <div className="mx-auto max-w-[1240px] space-y-6">
    <div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#778780]">Marketplace inventory</p><h1 className="mt-2 text-3xl font-black tracking-tight">Properties</h1><p className="mt-2 text-sm text-muted-foreground">Review, verify and maintain the accommodation catalogue.</p></div><Button className="bg-[#183a31] hover:bg-[#183a31]/90">Export inventory <ArrowRight className="size-4" /></Button></div>
    <div className="grid gap-4 sm:grid-cols-3"><Card className="border-black/5 shadow-sm"><CardContent className="p-5"><p className="text-xs font-bold uppercase tracking-[.15em] text-[#7c8a84]">Published</p><p className="mt-2 text-3xl font-black">42</p><p className="mt-1 text-xs text-muted-foreground">Live properties</p></CardContent></Card><Card className="border-black/5 shadow-sm"><CardContent className="p-5"><p className="text-xs font-bold uppercase tracking-[.15em] text-[#7c8a84]">Pending review</p><p className="mt-2 text-3xl font-black text-[#9a651e]">3</p><p className="mt-1 text-xs text-muted-foreground">Awaiting operator action</p></CardContent></Card><Card className="border-black/5 shadow-sm"><CardContent className="p-5"><p className="text-xs font-bold uppercase tracking-[.15em] text-[#7c8a84]">Verification coverage</p><p className="mt-2 text-3xl font-black">91%</p><p className="mt-1 text-xs text-muted-foreground">Level 3+ verification</p></CardContent></Card></div>
    <Card className="overflow-hidden border-black/5 shadow-sm"><CardHeader className="border-b border-black/5 px-5 py-4"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><CardTitle className="text-xl">Property inventory</CardTitle><p className="mt-1 text-xs text-muted-foreground">Search names and inspect verification state.</p></div><div className="relative w-full md:w-80"><Search className="absolute left-3 top-3 size-4 text-muted-foreground" /><Input className="bg-[#fafbf9] pl-9" placeholder="Search properties, districts..." /></div></div></CardHeader><CardContent className="p-0">
      <div className="hidden grid-cols-[1.9fr_1fr_1fr_1fr_44px] gap-4 border-b border-black/5 bg-[#fafbf9] px-5 py-3 text-[10px] font-bold uppercase tracking-[.12em] text-[#7d8c85] lg:grid"><span>Property</span><span>Location</span><span>Verification</span><span>Status</span><span /></div>
      {rows.map(([name, location, verification, status]) => <Link href="/admin/properties" key={name} className="grid gap-3 border-b border-black/5 px-5 py-4 transition hover:bg-[#fafbf9] last:border-0 lg:grid-cols-[1.9fr_1fr_1fr_1fr_44px] lg:items-center lg:gap-4"><div className="flex items-center gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-2xl bg-[#e8efea] text-[#1b5d47]"><Building2 className="size-5" /></span><div><p className="font-bold">{name}</p><p className="mt-1 text-xs text-muted-foreground lg:hidden">{location} · {verification}</p></div></div><p className="hidden text-sm text-muted-foreground lg:block">{location}</p><Badge variant="secondary" className="hidden w-fit text-[9px] uppercase lg:inline-flex">{verification}</Badge><div className="flex items-center gap-2"><span className={`size-2 rounded-full ${status === 'Published' ? 'bg-emerald-500' : 'bg-[#d4942f]'}`} /><span className="text-xs font-semibold">{status}</span></div><MoreHorizontal className="hidden size-4 text-muted-foreground lg:block" /></Link>)}
    </CardContent></Card>
    <div className="grid gap-4 md:grid-cols-2"><Card className="border-black/5 bg-[#eef3ee] shadow-sm"><CardContent className="flex items-start gap-3 p-5"><CheckCircle2 className="mt-0.5 size-5 text-[#2b7a5c]" /><div><p className="font-bold">Verification policy</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Platform verification and government tourism registration are shown as separate signals.</p></div></CardContent></Card><Card className="border-black/5 bg-[#fbf2e3] shadow-sm"><CardContent className="flex items-start gap-3 p-5"><ShieldAlert className="mt-0.5 size-5 text-[#9a651e]" /><div><p className="font-bold">Queue priority</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Process pending properties before launching new promotional inventory.</p></div></CardContent></Card></div>
  </div>
}
