import type { SupabaseClient } from '@supabase/supabase-js'
import type { Property, PropertyMedia, Room, VerificationLevel } from '@/types/domain'
import type { PropertyRepository, PropertySearchInput } from './property.repository'

const DEFAULT_PROPERTY_IMAGE='https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=1200&q=80'
const clamp=(value:number,min=0,max=1)=>Math.max(min,Math.min(max,value))
const distanceKm=(lat1:number,lon1:number,lat2:number,lon2:number)=>{const r=6371;const dLat=(lat2-lat1)*Math.PI/180;const dLon=(lon2-lon1)*Math.PI/180;const a=Math.sin(dLat/2)**2+Math.cos(lat1*Math.PI/180)*Math.cos(lat2*Math.PI/180)*Math.sin(dLon/2)**2;return 2*r*Math.asin(Math.sqrt(a))}

export class SupabasePropertyRepository implements PropertyRepository<Property>{
  constructor(private readonly db:SupabaseClient){}
  async listPublished(input?:PropertySearchInput):Promise<Property[]>{
    let query=this.db.from('properties').select(`id,slug,name,property_type,description,district,town,village,latitude,longitude,price_from,rating,review_count,hero_image,cancellation_policy,verification_level,tourism_registration_status,host_id,host:host_profiles!inner(display_name),rooms:rooms(id,name,description,max_guests,base_price,room_type,beds,bathroom_type),property_amenities(amenity:amenities(name)),property_media(id,url,alt_text,sort_order,is_hero,media_type,room_id)`).eq('status','PUBLISHED')
    const destination=input?.destination?.trim().toLowerCase(); if(destination) query=query.or(`name.ilike.%${destination}%,town.ilike.%${destination}%,district.ilike.%${destination}%,village.ilike.%${destination}%`)
    if(input?.district?.trim()) query=query.eq('district',input.district.trim()); if(input?.propertyType?.trim()) query=query.eq('property_type',input.propertyType.trim()); if(input?.minPrice!=null) query=query.gte('price_from',input.minPrice); if(input?.maxPrice!=null) query=query.lte('price_from',input.maxPrice); if(input?.minVerification!=null) query=query.gte('verification_level',input.minVerification)
    const {data,error}=await query; if(error){console.error('[PropertyRepository] listPublished error:',error.message);return []}
    let rows=data??[]
    if(input?.amenities?.length){const wanted=input.amenities.map(a=>a.toLowerCase());rows=rows.filter((row:any)=>{const names=(row.property_amenities??[]).map((pa:any)=>pa.amenity?.name?.toLowerCase()).filter(Boolean);return wanted.every(a=>names.includes(a))})}
    let properties=rows.map((row)=>this.toProperty(row))
    if(input?.guests&&input.guests>0) properties=properties.filter(p=>p.rooms.some(r=>r.maxGuests>=input.guests!))
    let availability=new Set<string>();
    if(input?.checkIn&&input?.checkOut&&input.checkOut>input.checkIn){const {data:inv}=await this.db.from('room_inventory').select('room_id,date,available_units,blocked_units').gte('date',input.checkIn).lt('date',input.checkOut); const byRoom=new Map<string,Set<string>>(); for(const r of inv??[]){if(Number(r.available_units)>0&&Number(r.blocked_units)===0){if(!byRoom.has(r.room_id))byRoom.set(r.room_id,new Set());byRoom.get(r.room_id)!.add(r.date)}} const start=new Date(`${input.checkIn}T00:00:00Z`);const end=new Date(`${input.checkOut}T00:00:00Z`);const nights=Math.max(0,Math.round((end.getTime()-start.getTime())/86400000)); properties=properties.filter(p=>p.rooms.some(room=>{const s=byRoom.get(room.id);if(!s||nights===0)return false;for(let i=0;i<nights;i++){const d=new Date(start.getTime()+i*86400000).toISOString().slice(0,10);if(!s.has(d))return false} availability.add(p.id);return true}))}
    if(input?.sort&&input.sort!=='relevance'){if(input.sort==='price_asc')properties.sort((a,b)=>a.priceFrom-b.priceFrom);else if(input.sort==='price_desc')properties.sort((a,b)=>b.priceFrom-a.priceFrom);else properties.sort((a,b)=>b.rating-a.rating);return properties}

    const ids=properties.map(p=>p.id); const conversion=new Map<string,{views:number;bookings:number}>();
    if(ids.length){const {data:events}=await this.db.from('analytics_events').select('event_name,properties').in('event_name',['property_viewed','booking_created']).gte('created_at',new Date(Date.now()-90*86400000).toISOString()).limit(10000); for(const e of events??[]){const propertyId=(e.properties as any)?.property_id ?? (e.properties as any)?.propertyId;if(!propertyId||!ids.includes(propertyId))continue;const row=conversion.get(propertyId)??{views:0,bookings:0};if(e.event_name==='property_viewed')row.views++;else row.bookings++;conversion.set(propertyId,row)}}
    let targetLat:number|undefined;let targetLon:number|undefined;if(destination){const {data}=await this.db.from('destinations').select('latitude,longitude').ilike('name',`%${destination}%`).limit(1).maybeSingle();targetLat=data?.latitude??undefined;targetLon=data?.longitude??undefined}
    return properties.sort((a,b)=>this.rank(b,input,availability,conversion,targetLat,targetLon)-this.rank(a,input,availability,conversion,targetLat,targetLon))
  }
  async findById(id:string){const {data,error}=await this.db.from('properties').select(`id,slug,name,property_type,description,district,town,village,latitude,longitude,price_from,rating,review_count,hero_image,cancellation_policy,verification_level,tourism_registration_status,host_id,host:host_profiles!inner(display_name),rooms:rooms(id,name,description,max_guests,base_price,room_type,beds,bathroom_type),property_amenities(amenity:amenities(name)),property_media(id,url,alt_text,sort_order,is_hero,media_type,room_id)`).eq('id',id).eq('status','PUBLISHED').maybeSingle();if(error||!data)return null;return this.toProperty(data)}
  async findBySlug(slug:string){const {data,error}=await this.db.from('properties').select(`id,slug,name,property_type,description,district,town,village,latitude,longitude,price_from,rating,review_count,hero_image,cancellation_policy,verification_level,tourism_registration_status,host_id,host:host_profiles!inner(display_name),rooms:rooms(id,name,description,max_guests,base_price,room_type,beds,bathroom_type),property_amenities(amenity:amenities(name)),property_media(id,url,alt_text,sort_order,is_hero,media_type,room_id)`).eq('slug',slug).eq('status','PUBLISHED').maybeSingle();if(error||!data)return null;return this.toProperty(data)}
  private rank(p:Property,input:PropertySearchInput|undefined,availability:Set<string>,conversion:Map<string,{views:number;bookings:number}>,targetLat?:number,targetLon?:number){
    const quality=clamp(p.rating/5);const verification=clamp(p.verificationLevel/4);const reviews=clamp(Math.log10(p.reviewCount+1)/3);const availabilityScore=input?.checkIn&&input?.checkOut?availability.has(p.id)?1:0.35:0.7;const priceScore=clamp(1/(1+(p.priceFrom||1)/2000));let distanceScore=0.5;if(targetLat!=null&&targetLon!=null&&p.latitude&&p.longitude){const d=distanceKm(targetLat,targetLon,p.latitude,p.longitude);distanceScore=clamp(1-d/80)}const cv=conversion.get(p.id)??{views:0,bookings:0};const conversionScore=clamp(cv.views?cv.bookings/cv.views:0.1);return availabilityScore*0.25+quality*0.14+verification*0.15+reviews*0.12+priceScore*0.10+distanceScore*0.10+conversionScore*0.14+ (p.tourismRegistered?0.05:0)
  }
  private toProperty(row:any):Property{const media:PropertyMedia[]=(row.property_media??[]).map((m:any)=>({id:m.id,url:m.url,altText:m.alt_text??'',sortOrder:Number(m.sort_order??0),isHero:Boolean(m.is_hero),roomId:m.room_id??null})).sort((a,b)=>a.sortOrder-b.sortOrder);const rooms:Room[]=(row.rooms??[]).map((r:any)=>({id:r.id,name:r.name,maxGuests:r.max_guests,beds:r.beds??'',bathroom:r.bathroom_type??'',price:Number(r.base_price??0),description:r.description??'',roomType:r.room_type??'',images:media.filter(m=>m.roomId===r.id)}));const amenities:string[]=(row.property_amenities??[]).map((pa:any)=>pa.amenity?.name).filter(Boolean);const hero=media.find(m=>m.isHero&&!m.roomId)?.url??media.find(m=>!m.roomId)?.url??row.hero_image??media[0]?.url??'';return {id:row.id,slug:row.slug,name:row.name,location:row.town??row.village??row.district??'',district:row.district??'',propertyType:row.property_type,description:row.description??'',priceFrom:Number(row.price_from??0),rating:Number(row.rating??0),reviewCount:Number(row.review_count??0),imageUrl:hero||DEFAULT_PROPERTY_IMAGE,amenities,verificationLevel:Number(row.verification_level??0) as VerificationLevel,tourismRegistered:row.tourism_registration_status==='VERIFIED',cancellation:row.cancellation_policy??'',hostName:row.host?.display_name??'',latitude:row.latitude??0,longitude:row.longitude??0,media,rooms}}
}
